#!/usr/bin/env bash
# Explicit-host provisioning for a dedicated SecureWave IKEv2 gateway.
#
# This script intentionally refuses a shared strongSwan installation.  The
# credential lifecycle helper reloads swanctl credentials with --clear so a
# shared daemon could lose unrelated credentials.  Run it only on a fresh,
# explicitly selected gateway after its Hetzner firewall permits UDP 500/4500.
set -euo pipefail

ROOT=/etc/securewave/ikev2
PKI="$ROOT/pki"
SWANCTL_CONF=/etc/swanctl/swanctl.conf
SWANCTL_DIR=/etc/swanctl/conf.d
SERVER_CONF="$SWANCTL_DIR/securewave.conf"
CA_CERT="$PKI/securewave-ikev2-ca.pem"
CA_KEY="$PKI/securewave-ikev2-ca-key.pem"
SERVER_CERT=/etc/swanctl/x509/securewave-ikev2-server.pem
SERVER_KEY=/etc/swanctl/private/securewave-ikev2-server-key.pem
SENTINEL="# SecureWave dedicated IKEv2 gateway"
SWANCTL=/usr/sbin/swanctl
NETWORK=/usr/local/libexec/securewave-ikev2-network
CREDENTIAL=/usr/local/libexec/securewave-ikev2-credential
HEALTH=/usr/local/libexec/securewave-ikev2-health
SERVICE=strongswan-swanctl.service

host=""
dns=94.140.14.14
pool=10.77.0.0/24
admin_user="${SECUREWAVE_SERVER_ADMIN:-securewave}"

usage() {
  cat >&2 <<'EOF'
Usage: provision_ikev2_server.sh --public-host HOST [--dns IPv4] [--pool 10.x.y.0/24]
       provision_ikev2_server.sh --print-ca

HOST must be the public DNS name or numeric address embedded in the gateway
certificate and recorded as ikev2_remote_id.  This is a dedicated-gateway
operation; it refuses a shared strongSwan/swanctl installation.
EOF
}

valid_ipv4() {
  local address="$1"
  local octet
  local -a values
  [[ "$address" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
  IFS=. read -r -a values <<<"$address"
  for octet in "${values[@]}"; do
    (( 10#$octet <= 255 )) || return 1
  done
}

valid_private_pool() {
  local cidr="$1"
  local address prefix host_bits numeric a b c d
  IFS=/ read -r address prefix <<<"$cidr"
  [[ -n "$address" && -n "$prefix" && "$cidr" == "$address/$prefix" ]] || return 1
  [[ "$prefix" =~ ^(1[6-9]|2[0-9]|30)$ ]] || return 1
  valid_ipv4 "$address" || return 1
  [[ "${address%%.*}" == "10" ]] || return 1
  IFS=. read -r a b c d <<<"$address"
  numeric=$(( (10#$a << 24) | (10#$b << 16) | (10#$c << 8) | 10#$d ))
  host_bits=$((32 - 10#$prefix))
  (( (numeric & ((1 << host_bits) - 1)) == 0 ))
}

while (($#)); do
  case "$1" in
    --public-host) host="${2:-}"; shift 2 ;;
    --dns) dns="${2:-}"; shift 2 ;;
    --pool) pool="${2:-}"; shift 2 ;;
    --print-ca)
      [[ -r "$CA_CERT" ]] || { echo "SecureWave IKEv2 CA is not provisioned." >&2; exit 1; }
      cat "$CA_CERT"
      exit 0
      ;;
    --help|-h) usage; exit 0 ;;
    *) usage; exit 64 ;;
  esac
done

[[ ${EUID} -eq 0 ]] || { echo "Run as root on the explicitly authorized gateway." >&2; exit 64; }
[[ "$host" =~ ^[A-Za-z0-9][A-Za-z0-9:.-]{0,252}$ ]] || { usage; exit 64; }
valid_ipv4 "$dns" || { echo "DNS must be a valid IPv4 literal." >&2; exit 64; }
valid_private_pool "$pool" || {
  echo "Pool must be an RFC1918 10/16-30 IPv4 CIDR." >&2
  exit 64
}
[[ "$admin_user" =~ ^[a-z_][a-z0-9_-]{0,31}$ ]] || { echo "Invalid server admin." >&2; exit 64; }

if systemctl is-active --quiet strongswan-starter.service || \
   systemctl is-enabled --quiet strongswan-starter.service 2>/dev/null; then
  echo "Refusing a host with strongswan-starter enabled or active; use a dedicated charon-systemd gateway." >&2
  exit 1
fi

if [[ -d "$SWANCTL_DIR" ]] && find "$SWANCTL_DIR" -maxdepth 1 -type f \
  ! -name 'securewave.conf' ! -name 'securewave-eap-*.conf' -print -quit | grep -q .; then
  echo "Refusing a shared /etc/swanctl/conf.d installation." >&2
  exit 1
fi
if [[ -s "$SWANCTL_CONF" ]] && ! grep -Fqx "$SENTINEL" "$SWANCTL_CONF"; then
  if grep -Ev '^[[:space:]]*(#|$|include[[:space:]]+conf\.d/\*\.conf)$' "$SWANCTL_CONF" | grep -q .; then
    echo "Refusing an existing non-SecureWave swanctl configuration." >&2
    exit 1
  fi
fi

apt-get update
apt-get install -y --no-install-recommends \
  charon-systemd strongswan-swanctl strongswan-pki libcharon-extra-plugins \
  libcharon-extauth-plugins libstrongswan-standard-plugins iproute2 iptables

id "$admin_user" >/dev/null 2>&1 || { echo "Configured server admin does not exist." >&2; exit 1; }
command -v "$SWANCTL" >/dev/null 2>&1 || { echo "swanctl is unavailable after installation." >&2; exit 1; }
command -v pki >/dev/null 2>&1 || { echo "strongSwan pki utility is unavailable after installation." >&2; exit 1; }

install -d -m 0700 "$ROOT" "$PKI"
install -d -m 0700 /etc/swanctl/private
install -d -m 0755 /etc/swanctl/x509 "$SWANCTL_DIR" /usr/local/libexec

if [[ -s "$SWANCTL_CONF" ]] && ! grep -Fqx "$SENTINEL" "$SWANCTL_CONF"; then
  install -m 0600 "$SWANCTL_CONF" "$ROOT/swanctl.conf.pre-securewave"
fi
cat >"$SWANCTL_CONF" <<EOF
$SENTINEL
# Generated by SecureWave.  Do not add non-SecureWave connections here.
include conf.d/*.conf
EOF
chmod 0644 "$SWANCTL_CONF"

if [[ ! -s "$CA_CERT" || ! -s "$CA_KEY" ]]; then
  umask 077
  pki --gen --type ed25519 --outform pem >"$CA_KEY"
  pki --self --ca --lifetime 3650 --in "$CA_KEY" --type ed25519 \
    --dn "CN=SecureWave IKEv2 CA" --outform pem >"$CA_CERT"
fi
if [[ ! -s "$SERVER_CERT" || ! -s "$SERVER_KEY" ]]; then
  umask 077
  pki --gen --type ed25519 --outform pem >"$SERVER_KEY"
  pki --pub --in "$SERVER_KEY" | \
    pki --issue --lifetime 825 --cacert "$CA_CERT" --cakey "$CA_KEY" \
      --dn "CN=$host" --san "$host" --flag serverAuth --outform pem >"$SERVER_CERT"
fi
chmod 0600 "$CA_KEY" "$SERVER_KEY"
chmod 0644 "$CA_CERT" "$SERVER_CERT"

cat >"$SERVER_CONF" <<EOF
# SecureWave dedicated IKEv2 gateway configuration.
connections {
  securewave {
    version = 2
    local_addrs = %any
    proposals = aes256gcm16-prfsha256-ecp256,aes256-sha256-modp2048
    rekey_time = 30m
    reauth_time = 10m
    over_time = 2m
    dpd_delay = 30s
    dpd_timeout = 120s
    unique = replace
    pools = securewave-ipv4
    local {
      auth = pubkey
      certs = securewave-ikev2-server.pem
      id = "$host"
    }
    remote {
      auth = eap-mschapv2
      eap_id = %any
    }
    children {
      securewave-net {
        local_ts = 0.0.0.0/0
        rekey_time = 20m
        dpd_action = clear
        start_action = none
      }
    }
  }
}
pools {
  securewave-ipv4 {
    addrs = "$pool"
    dns = "$dns"
  }
}
EOF
chmod 0600 "$SERVER_CONF"

cat >"$CREDENTIAL" <<'EOF'
#!/usr/bin/env bash
# Fixed-command EAP credential lifecycle for the dedicated SecureWave gateway.
set -euo pipefail
ROOT=/etc/securewave/ikev2
CONF_DIR=/etc/swanctl/conf.d
SWANCTL=/usr/sbin/swanctl
op="${1:-}"
username="${2:-}"
[[ $# -eq 2 && "$username" =~ ^swikev2-[a-f0-9]{32}$ ]] || exit 64
target="$CONF_DIR/securewave-eap-${username}.conf"
lock="$ROOT/credentials.lock"
case "$op" in
  upsert)
    IFS= read -r password || true
    [[ "$password" =~ ^[A-Za-z0-9_-]{32,128}$ ]] || exit 64
    # Accept exactly one line of secret input.  Password tokens cannot contain
    # whitespace, quotes, or shell-sensitive characters.
    if IFS= read -r extra; then
      [[ -z "$extra" ]] || exit 64
    fi
    ;;
  revoke) ;;
  *) exit 64 ;;
esac
exec 9>"$lock"
flock -x 9
previous=""
if [[ -f "$target" ]]; then
  previous="$(mktemp "$ROOT/.credential.previous.XXXXXX")"
  install -m 0600 "$target" "$previous"
fi
restore_previous() {
  if [[ -n "$previous" ]]; then
    install -m 0600 "$previous" "$target"
  else
    rm -f "$target"
  fi
  "$SWANCTL" --load-all --clear --noprompt >/dev/null 2>&1 || true
  rm -f "$previous"
}
if [[ "$op" == upsert ]]; then
  temp="$(mktemp "$CONF_DIR/.securewave-eap.XXXXXX")"
  chmod 0600 "$temp"
  printf 'secrets {\n  eap-%s {\n    id = "%s"\n    secret = "%s"\n  }\n}\n' \
    "$username" "$username" "$password" >"$temp"
  mv -f "$temp" "$target"
else
  rm -f "$target"
fi
if ! "$SWANCTL" --load-all --clear --noprompt >/dev/null; then
  restore_previous
  exit 1
fi
rm -f "$previous"
printf 'OK\n'
EOF
chmod 0700 "$CREDENTIAL"

cat >"$NETWORK" <<'EOF'
#!/usr/bin/env bash
# Install only tagged SecureWave gateway firewall/NAT state.
set -euo pipefail
# The provisioning wrapper replaces this literal after validation.
POOL=10.77.0.0/24
CHAIN_INPUT=SECUREWAVE_IKEV2_INPUT
CHAIN_FORWARD=SECUREWAVE_IKEV2_FORWARD
TAG_INPUT=securewave-ikev2-input-v1
TAG_NAT=securewave-ikev2-nat-v1

cleanup() {
  while iptables -t nat -D POSTROUTING -s "$POOL" -m comment --comment "$TAG_NAT" -j MASQUERADE >/dev/null 2>&1; do :; done
  while iptables -D INPUT -j "$CHAIN_INPUT" >/dev/null 2>&1; do :; done
  while iptables -D FORWARD -j "$CHAIN_FORWARD" >/dev/null 2>&1; do :; done
  iptables -F "$CHAIN_INPUT" >/dev/null 2>&1 || true
  iptables -X "$CHAIN_INPUT" >/dev/null 2>&1 || true
  iptables -F "$CHAIN_FORWARD" >/dev/null 2>&1 || true
  iptables -X "$CHAIN_FORWARD" >/dev/null 2>&1 || true
}

case "${1:-}" in
  ensure)
    cleanup
    trap cleanup ERR
    uplink="$(ip -4 route show default | awk '{ for (i = 1; i <= NF; i++) if ($i == "dev") { print $(i + 1); exit } }')"
    [[ "$uplink" =~ ^[A-Za-z0-9_.:-]+$ ]] || exit 1
    iptables -N "$CHAIN_INPUT"
    iptables -A "$CHAIN_INPUT" -p udp --dport 500 -m comment --comment "$TAG_INPUT" -j ACCEPT
    iptables -A "$CHAIN_INPUT" -p udp --dport 4500 -m comment --comment "$TAG_INPUT" -j ACCEPT
    iptables -I INPUT 1 -j "$CHAIN_INPUT"
    iptables -N "$CHAIN_FORWARD"
    iptables -A "$CHAIN_FORWARD" -s "$POOL" -o "$uplink" -j ACCEPT
    iptables -A "$CHAIN_FORWARD" -d "$POOL" -i "$uplink" -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    iptables -I FORWARD 1 -j "$CHAIN_FORWARD"
    iptables -t nat -A POSTROUTING -s "$POOL" -o "$uplink" -m comment --comment "$TAG_NAT" -j MASQUERADE
    trap - ERR
    ;;
  cleanup) cleanup ;;
  *) exit 64 ;;
esac
EOF
# Do not let an environment variable control routing state in the installed
# helper.  The CIDR was syntax-validated before this literal replacement.
sed -i "s|POOL=10.77.0.0/24|POOL=$pool|" "$NETWORK"
chmod 0700 "$NETWORK"

cat >"$HEALTH" <<EOF
#!/usr/bin/env bash
set -euo pipefail
systemctl is-active --quiet $SERVICE
systemctl is-active --quiet securewave-ikev2-network.service
test -s $CA_CERT && test -s $SERVER_CERT && test -s $SERVER_KEY
test -x $CREDENTIAL && test -x $NETWORK
$SWANCTL --list-conns | grep -Eq '^securewave:'
ss -H -lun | grep -Eq '(:|\\])500([[:space:]]|$)'
ss -H -lun | grep -Eq '(:|\\])4500([[:space:]]|$)'
printf 'OK\\n'
EOF
chmod 0700 "$HEALTH"

cat >/etc/systemd/system/securewave-ikev2-load.service <<EOF
[Unit]
Description=Load SecureWave dedicated IKEv2 swanctl configuration
Requires=$SERVICE
After=$SERVICE
PartOf=$SERVICE

[Service]
Type=oneshot
ExecStart=$SWANCTL --load-all --clear --noprompt

[Install]
RequiredBy=$SERVICE
EOF

cat >/etc/systemd/system/securewave-ikev2-network.service <<EOF
[Unit]
Description=SecureWave IKEv2 owned forwarding and NAT rules
After=network-online.target $SERVICE
Wants=network-online.target
Requires=$SERVICE

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=$NETWORK ensure
ExecStop=$NETWORK cleanup

[Install]
WantedBy=multi-user.target
EOF

install -m 0440 /dev/stdin /etc/sudoers.d/securewave-ikev2 <<EOF
$admin_user ALL=(root) NOPASSWD: $HEALTH, $CREDENTIAL upsert *, $CREDENTIAL revoke *
EOF

printf 'net.ipv4.ip_forward=1\n' >/etc/sysctl.d/99-securewave-ikev2.conf
sysctl -w net.ipv4.ip_forward=1 >/dev/null
systemctl daemon-reload
systemctl enable --now "$SERVICE"
systemctl enable --now securewave-ikev2-load.service securewave-ikev2-network.service
"$HEALTH" >/dev/null

echo "IKEv2 runtime provisioned on a dedicated host. Retrieve only its public CA with: $0 --print-ca"
echo "Before metadata sync, record authenticated control-plane and live data-plane evidence; this script does not enable API availability."
