# auth package — token lifecycle, refresh rotation, revocation
"""Autogenerated SecureWave module overview.

This package initializer wires together the `auth` package for the SecureWave backend.
See `docs/code-explanations/auth/__init__.md` for the generated line-range walkthrough.
"""
