"""Autogenerated SecureWave module overview.

This module exposes API handlers for diagnostics features in the SecureWave backend.
See `docs/code-explanations/routes/diagnostics.md` for the generated line-range walkthrough.
"""

import json
import logging
import threading
from collections import deque
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, List
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from config.settings import get_settings
from database.session import get_db
from models.audit_log import AuditLog
from services.jwt_service import get_current_user
from utils.structured_logging import log_event

router = APIRouter(prefix="/api/diagnostics", tags=["diagnostics"])
SETTINGS = get_settings()
logger = logging.getLogger(__name__)


# ============================================
# Telemetry Ingestion (Day 5)
# ============================================

class TelemetryPayload(BaseModel):
    """Telemetry data from VPN clients"""
    latency_ms: float
    packet_loss: float = 0.0
    jitter_ms: float = 0.0
    uptime_seconds: int = 0
    bytes_sent: int = 0
    bytes_received: int = 0
    server_id: Optional[str] = None
    connection_quality: Optional[str] = None  # "excellent", "good", "fair", "poor"


class TelemetryBatch(BaseModel):
    """Batch of telemetry records"""
    records: List[TelemetryPayload]


class _TelemetryStore:
    """Bounded JSONL telemetry store with size-based rotation."""

    def __init__(self, path: Path, *, max_records: int = 10_000, max_bytes: int = 2 * 1024 * 1024) -> None:
        self._path = path
        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()
        self._max_records = max_records
        self._max_bytes = max_bytes

    def append(self, record: dict) -> str:
        line = json.dumps(record, sort_keys=True)
        with self._lock:
            with self._path.open("a", encoding="utf-8") as handle:
                handle.write(line + "\n")
            self._rotate_unlocked()
        return f"{record['timestamp']}:{record['user_id']}"

    def append_many(self, records: List[dict]) -> int:
        if not records:
            return 0
        with self._lock:
            with self._path.open("a", encoding="utf-8") as handle:
                for record in records:
                    handle.write(json.dumps(record, sort_keys=True) + "\n")
            self._rotate_unlocked()
        return len(records)

    def clear(self) -> None:
        with self._lock:
            self._path.write_text("", encoding="utf-8")

    def __len__(self) -> int:
        with self._lock:
            return sum(1 for line in self._iter_lines_unlocked() if line)

    def recent_for_user(self, user_id: int, *, limit: int) -> List[dict]:
        with self._lock:
            tail: deque[dict] = deque(maxlen=limit)
            for line in self._iter_lines_unlocked():
                if not line:
                    continue
                try:
                    record = json.loads(line)
                except json.JSONDecodeError:
                    logger.debug("Skipping malformed telemetry line while reading recent entries")
                    continue
                if record.get("user_id") == user_id:
                    tail.append(record)
            return list(tail)

    def _iter_lines_unlocked(self):
        if not self._path.exists():
            return []
        with self._path.open("r", encoding="utf-8") as handle:
            return [line.strip() for line in handle if line.strip()]

    def _rotate_unlocked(self) -> None:
        if not self._path.exists():
            return
        try:
            stat = self._path.stat()
        except OSError as exc:
            logger.debug("Telemetry store stat failed: %s", exc)
            return
        if stat.st_size <= self._max_bytes:
            current_count = 0
            with self._path.open("r", encoding="utf-8") as handle:
                for current_count, _ in enumerate(handle, start=1):
                    if current_count > self._max_records:
                        break
            if current_count <= self._max_records:
                return

        raw_lines: deque[str] = deque(maxlen=self._max_records)
        with self._path.open("r", encoding="utf-8") as handle:
            for line in handle:
                stripped = line.strip()
                if stripped:
                    raw_lines.append(stripped)

        while raw_lines and sum(len(line.encode("utf-8")) + 1 for line in raw_lines) > self._max_bytes:
            raw_lines.popleft()

        rotated = "\n".join(raw_lines)
        self._path.write_text((rotated + "\n") if rotated else "", encoding="utf-8")


_telemetry_store = _TelemetryStore(
    Path("artifacts/telemetry/client_telemetry.jsonl"),
)


@router.post("/telemetry")
def ingest_telemetry(
    payload: TelemetryPayload,
    current_user=Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Ingest telemetry from VPN client.
    Stores latency, packet loss, uptime metrics.
    (Day 5: Telemetry ingestion endpoint)
    """
    if not SETTINGS.telemetry_enabled:
        raise HTTPException(status_code=503, detail="Telemetry ingestion disabled")

    record = {
        "user_id": current_user.id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "latency_ms": payload.latency_ms,
        "packet_loss": payload.packet_loss,
        "jitter_ms": payload.jitter_ms,
        "uptime_seconds": payload.uptime_seconds,
        "bytes_sent": payload.bytes_sent,
        "bytes_received": payload.bytes_received,
        "server_id": payload.server_id,
        "connection_quality": payload.connection_quality,
    }

    record_id = _telemetry_store.append(record)

    # Update optimizer with fresh metrics if server_id provided
    if payload.server_id:
        try:
            from services.vpn_optimizer import get_vpn_optimizer
            optimizer = get_vpn_optimizer()
            optimizer.update_server_metrics(payload.server_id, {
                "latency_ms": payload.latency_ms,
                "packet_loss": payload.packet_loss,
                "jitter_ms": payload.jitter_ms,
            })
        except Exception as exc:
            logger.debug("Telemetry optimizer update failed for %s: %s", payload.server_id, exc)

    log_event(
        logger,
        "metrics_submission",
        user_id=current_user.id,
        server_id=payload.server_id,
        record_count=1,
        latency_ms=payload.latency_ms,
    )
    return {"status": "accepted", "record_id": record_id}


@router.post("/telemetry/batch")
def ingest_telemetry_batch(
    batch: TelemetryBatch,
    current_user=Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Ingest multiple telemetry records at once"""
    if not SETTINGS.telemetry_enabled:
        raise HTTPException(status_code=503, detail="Telemetry ingestion disabled")

    accepted_records: List[dict] = []
    for payload in batch.records:
        record = {
            "user_id": current_user.id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "latency_ms": payload.latency_ms,
            "packet_loss": payload.packet_loss,
            "jitter_ms": payload.jitter_ms,
            "uptime_seconds": payload.uptime_seconds,
            "bytes_sent": payload.bytes_sent,
            "bytes_received": payload.bytes_received,
            "server_id": payload.server_id,
        }
        accepted_records.append(record)
        if payload.server_id:
            try:
                from services.vpn_optimizer import get_vpn_optimizer
                optimizer = get_vpn_optimizer()
                optimizer.update_server_metrics(payload.server_id, {
                    "latency_ms": payload.latency_ms,
                    "packet_loss": payload.packet_loss,
                    "jitter_ms": payload.jitter_ms,
                })
            except Exception as exc:
                logger.debug("Telemetry batch optimizer update failed for %s: %s", payload.server_id, exc)

    accepted = _telemetry_store.append_many(accepted_records)

    log_event(
        logger,
        "metrics_submission",
        user_id=current_user.id,
        record_count=accepted,
        server_ids=sorted({payload.server_id for payload in batch.records if payload.server_id}),
    )
    return {"status": "accepted", "records_accepted": accepted}


# ============================================
# Debug Session Endpoint (Day 10)
# ============================================

@router.get("/debug/session")
def debug_session(
    current_user=Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Debug endpoint for session observability.
    Shows current user session state, VPN status, optimizer stats.
    (Day 10: /debug/session endpoint)
    """
    vpn_status = None

    # Get optimizer stats
    optimizer_stats = None
    try:
        from services.vpn_optimizer import get_vpn_optimizer
        optimizer = get_vpn_optimizer()
        optimizer_stats = optimizer.get_stats()
    except Exception as e:
        optimizer_stats = {"error": str(e)}

    # Get recent telemetry for this user
    user_telemetry = _telemetry_store.recent_for_user(current_user.id, limit=10)

    return {
        "user": {
            "id": current_user.id,
            "email": current_user.email,
            "is_active": current_user.is_active,
            "subscription_status": current_user.subscription_status,
            "has_wg_keys": bool(current_user.wg_public_key),
        },
        "vpn_session": vpn_status,
        "optimizer": optimizer_stats,
        "recent_telemetry": user_telemetry,
        "telemetry_store_size": len(_telemetry_store),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


@router.get("/summary")
def diagnostics_summary(
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user)
):
    env = SETTINGS.environment
    db_url = SETTINGS.database_url
    db_type = "sqlite" if db_url.startswith("sqlite") else "postgres"

    return {
        "environment": env,
        "database": db_type,
        "telemetry_enabled": SETTINGS.telemetry_enabled,
        "user_id": current_user.id,
    }


@router.get("/events")
def diagnostics_events(
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user)
):
    if not current_user.is_admin:
        raise HTTPException(status_code=403, detail="Admin access required")
    events = (
        db.query(AuditLog)
        .order_by(AuditLog.created_at.desc())
        .limit(20)
        .all()
    )
    return [event.to_dict() for event in events]
