"""Autogenerated SecureWave module overview.

This service module implements the business logic for server bootstrap operations.
See `docs/code-explanations/services/server_bootstrap.md` for the generated line-range walkthrough.
"""

from __future__ import annotations

import base64
import ipaddress
import logging
import os
import subprocess
from pathlib import Path

from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from models.vpn_server import VPNServer

logger = logging.getLogger(__name__)

_PLACEHOLDER_PUBLIC_IP = "138.199.204.139"
_PLACEHOLDER_WG_PORT = 51820

_DEFAULT_SERVERS = (
    {
        "server_id": "de-nue-1",
        "location": "Nuremberg",
        "country": "Germany",
        "country_code": "DE",
        "city": "Nuremberg",
        "region": "Europe",
        "hcloud_location": "nbg1",
        "wg_public_key": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",  # placeholder
        "tier_restriction": None,
    },
    {
        "server_id": "de-fra-1",
        "location": "Frankfurt",
        "country": "Germany",
        "country_code": "DE",
        "city": "Frankfurt",
        "region": "Europe",
        "hcloud_location": "fsn1",
        "wg_public_key": "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE=",  # placeholder
        "tier_restriction": None,
    },
    {
        "server_id": "ch-zrh-1",
        "location": "Zurich",
        "country": "Switzerland",
        "country_code": "CH",
        "city": "Zurich",
        "region": "Europe",
        "hcloud_location": "fsn1",
        "wg_public_key": "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI=",  # placeholder
        "tier_restriction": "premium",
    },
    {
        "server_id": "nl-ams-1",
        "location": "Amsterdam",
        "country": "Netherlands",
        "country_code": "NL",
        "city": "Amsterdam",
        "region": "Europe",
        "hcloud_location": "fsn1",
        "wg_public_key": "AwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM=",  # placeholder
        "tier_restriction": "premium",
    },
    {
        "server_id": "fr-par-1",
        "location": "Paris",
        "country": "France",
        "country_code": "FR",
        "city": "Paris",
        "region": "Europe",
        "hcloud_location": "fsn1",
        "wg_public_key": "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ=",  # placeholder
        "tier_restriction": "premium",
    },
)

_PLACEHOLDER_KEY_MARKERS = (
    "AAAA",
    "AQEB",
    "bootstrap-placeholder",
)
_TRUE_VALUES = {"1", "true", "yes", "on"}


def _is_production_environment() -> bool:
    return (os.getenv("ENVIRONMENT") or os.getenv("environment") or "").strip().lower() == "production"


def _runtime_bootstrap_enabled() -> bool:
    if os.getenv("TESTING", "").strip().lower() in _TRUE_VALUES:
        return os.getenv("SECUREWAVE_TEST_ENABLE_RUNTIME_BOOTSTRAP", "").strip().lower() in _TRUE_VALUES
    return True


def _is_placeholder_value(value: str | None) -> bool:
    candidate = (value or "").strip()
    if not candidate:
        return False
    return any(marker in candidate for marker in _PLACEHOLDER_KEY_MARKERS)


def _validate_wireguard_public_key(server_id: str, public_key: str) -> None:
    candidate = (public_key or "").strip()
    if not candidate:
        raise RuntimeError(f"Default VPN server {server_id} is missing a WireGuard public key")
    try:
        decoded = base64.b64decode(candidate, validate=True)
    except Exception as exc:  # pragma: no cover - defensive path
        raise RuntimeError(f"Default VPN server {server_id} has an invalid WireGuard public key") from exc
    if len(decoded) != 32:
        raise RuntimeError(f"Default VPN server {server_id} has an invalid WireGuard public key length")


def _validate_server_seed_material(server_id: str, public_key: str) -> None:
    _validate_wireguard_public_key(server_id, public_key)
    if _is_production_environment() and _is_placeholder_value(public_key):
        raise RuntimeError(
            f"Refusing to bootstrap default VPN server {server_id} with placeholder WireGuard credentials in production"
        )


def _run_stdout(cmd: list[str]) -> str:
    try:
        result = subprocess.run(
            cmd,
            check=True,
            text=True,
            capture_output=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError, OSError):
        return ""
    return result.stdout.strip()


def _read_first(paths: list[Path]) -> str | None:
    for path in paths:
        try:
            text = path.read_text(encoding="utf-8").strip()
        except OSError:
            continue
        if text:
            return text
    return None


def _read_optional_pem_from_env(*, pem_env: str, path_env: str) -> str | None:
    raw = os.getenv(pem_env, "").strip()
    if raw:
        return raw
    path = os.getenv(path_env, "").strip()
    if not path:
        return None
    return _read_first([Path(path)])


def _detect_public_ip() -> str | None:
    override = os.getenv("SECUREWAVE_SERVER_PUBLIC_IP", "").strip()
    if override:
        return override

    raw = _run_stdout(["hostname", "-I"])
    ips = [part for part in raw.split() if part]
    for candidate in ips:
        try:
            ip = ipaddress.ip_address(candidate)
        except ValueError:
            continue
        if isinstance(ip, ipaddress.IPv4Address) and not (
            ip.is_loopback or ip.is_private or ip.is_link_local
        ):
            return candidate
    if ips:
        return ips[0]

    route = _run_stdout(["ip", "-4", "route", "get", "1.1.1.1"])
    parts = route.split()
    for index, part in enumerate(parts[:-1]):
        if part == "src":
            return parts[index + 1]
    return None


def _detect_wireguard_public_key() -> str | None:
    override = os.getenv("SECUREWAVE_WG_PUBLIC_KEY", "").strip()
    if override:
        return override

    key = _run_stdout(["wg", "show", "wg0", "public-key"])
    if key:
        return key
    return _read_first(
        [
            Path("/etc/wireguard/public.key"),
            Path("/etc/securewave/wireguard/public.key"),
            Path("/etc/wireguard/keys/server_public.key"),
        ]
    )


def _detect_openvpn_runtime(host_ip: str | None) -> tuple[bool, str | None, int, str, str | None]:
    ca_pem = _read_optional_pem_from_env(
        pem_env="SECUREWAVE_OPENVPN_CA_CERT_PEM",
        path_env="SECUREWAVE_OPENVPN_CA_CERT_PATH",
    ) or _read_first([Path("/etc/openvpn/server/ca.crt")])
    endpoint = os.getenv("SECUREWAVE_OPENVPN_ENDPOINT", "").strip() or host_ip
    port = int(os.getenv("SECUREWAVE_OPENVPN_PORT", "1194").strip() or "1194")
    transport = os.getenv("SECUREWAVE_OPENVPN_TRANSPORT", "").strip().lower() or "udp"

    conf_path = Path("/etc/openvpn/server/server.conf")
    if conf_path.exists():
        try:
            for line in conf_path.read_text(encoding="utf-8").splitlines():
                stripped = line.strip()
                if not stripped or stripped.startswith("#") or stripped.startswith(";"):
                    continue
                parts = stripped.split()
                if len(parts) < 2:
                    continue
                if parts[0] == "port" and "SECUREWAVE_OPENVPN_PORT" not in os.environ:
                    try:
                        port = int(parts[1])
                    except ValueError:
                        pass
                elif parts[0] == "proto" and "SECUREWAVE_OPENVPN_TRANSPORT" not in os.environ:
                    transport = parts[1].lower()
        except OSError:
            pass

    if transport not in {"udp", "tcp"}:
        transport = "udp"
    enabled = bool(endpoint and ca_pem)
    return enabled, endpoint, port, transport, ca_pem


def _detect_ikev2_runtime(host_ip: str | None) -> tuple[bool, str | None, str | None]:
    ca_pem = _read_optional_pem_from_env(
        pem_env="SECUREWAVE_IKEV2_CA_CERT_PEM",
        path_env="SECUREWAVE_IKEV2_CA_CERT_PATH",
    ) or _read_first(
        [
            Path("/etc/ipsec.d/cacerts/securewave-ikev2-ca-cert.pem"),
            Path("/etc/ipsec.d/cacerts/ca-cert.pem"),
        ]
    )

    remote_id = os.getenv("SECUREWAVE_IKEV2_REMOTE_ID", "").strip() or None
    if remote_id is None:
        conf_path = Path("/etc/ipsec.conf")
        try:
            for line in conf_path.read_text(encoding="utf-8").splitlines():
                stripped = line.strip()
                if stripped.startswith("leftid="):
                    candidate = stripped.split("=", 1)[1].strip()
                    if candidate:
                        remote_id = candidate
                        break
        except OSError:
            pass
    if not remote_id:
        remote_id = host_ip

    enabled = bool(host_ip and ca_pem)
    return enabled, remote_id, ca_pem


def _runtime_seed_material() -> dict[str, object]:
    if not _runtime_bootstrap_enabled():
        return {
            "public_ip": None,
            "wg_public_key": None,
            "wg_port": _PLACEHOLDER_WG_PORT,
            "supports_openvpn": False,
            "openvpn_endpoint": None,
            "openvpn_port": 1194,
            "openvpn_transport": "udp",
            "openvpn_ca_cert_pem": None,
            "supports_ikev2": False,
            "ikev2_remote_id": None,
            "ikev2_ca_cert_pem": None,
        }

    public_ip = _detect_public_ip()
    wg_public_key = _detect_wireguard_public_key()
    supports_openvpn, openvpn_endpoint, openvpn_port, openvpn_transport, openvpn_ca_cert_pem = (
        _detect_openvpn_runtime(public_ip)
    )
    supports_ikev2, ikev2_remote_id, ikev2_ca_cert_pem = _detect_ikev2_runtime(public_ip)
    return {
        "public_ip": public_ip,
        "wg_public_key": wg_public_key,
        "wg_port": _PLACEHOLDER_WG_PORT,
        "supports_openvpn": supports_openvpn,
        "openvpn_endpoint": openvpn_endpoint,
        "openvpn_port": openvpn_port,
        "openvpn_transport": openvpn_transport,
        "openvpn_ca_cert_pem": openvpn_ca_cert_pem,
        "supports_ikev2": supports_ikev2,
        "ikev2_remote_id": ikev2_remote_id,
        "ikev2_ca_cert_pem": ikev2_ca_cert_pem,
    }


def ensure_default_servers(session: Session) -> None:
    """
    Ensure the default server inventory exists.

    The existing schema has no `region_code` field, so the requested region
    codes are persisted in `VPNServer.server_id`.
    """
    default_ids = [str(item["server_id"]) for item in _DEFAULT_SERVERS]
    existing_ids = {
        row[0]
        for row in session.query(VPNServer.server_id)
        .filter(VPNServer.server_id.in_(default_ids))
        .all()
    }

    runtime = _runtime_seed_material()
    public_ip = str(runtime["public_ip"] or _PLACEHOLDER_PUBLIC_IP)
    wg_public_key = str(runtime["wg_public_key"] or "")
    inserted = 0
    for item in _DEFAULT_SERVERS:
        server_id = str(item["server_id"])
        server = None
        if server_id in existing_ids:
            server = session.query(VPNServer).filter(VPNServer.server_id == server_id).first()
        if server is None:
            server = VPNServer(server_id=server_id)
            inserted += 1
            existing_ids.add(server_id)

        resolved_wg_public_key = wg_public_key or str(item["wg_public_key"])
        _validate_server_seed_material(server_id, resolved_wg_public_key)

        server.location = str(item["location"])
        server.country = str(item["country"])
        server.country_code = str(item["country_code"])
        server.city = str(item["city"])
        server.region = str(item["region"])
        server.hcloud_location = str(item["hcloud_location"])
        server.public_ip = public_ip
        server.endpoint = f"{public_ip}:{int(runtime['wg_port'])}"
        server.wg_listen_port = int(runtime["wg_port"])
        server.wg_public_key = resolved_wg_public_key
        if not (server.wg_private_key_encrypted or "").strip() or _is_placeholder_value(server.wg_private_key_encrypted):
            server.wg_private_key_encrypted = ""
        server.protocol = "wireguard"
        server.supports_wireguard = True
        server.status = "active"
        server.health_status = "healthy"
        server.hcloud_server_state = "running"
        server.priority_weight = 100
        server.tier_restriction = item["tier_restriction"]

        if bool(runtime["supports_openvpn"]):
            server.supports_openvpn = True
            server.openvpn_endpoint = str(runtime["openvpn_endpoint"] or public_ip)
            server.openvpn_port = int(runtime["openvpn_port"])
            server.openvpn_transport = str(runtime["openvpn_transport"] or "udp")
            server.openvpn_ca_cert_pem = str(runtime["openvpn_ca_cert_pem"] or "")
        else:
            server.supports_openvpn = False
            server.openvpn_endpoint = None
            server.openvpn_ca_cert_pem = None

        if bool(runtime["supports_ikev2"]):
            server.supports_ikev2 = True
            server.ikev2_remote_id = str(runtime["ikev2_remote_id"] or public_ip)
            server.ikev2_ca_cert_pem = str(runtime["ikev2_ca_cert_pem"] or "")
        else:
            server.supports_ikev2 = False
            server.ikev2_remote_id = None
            server.ikev2_ca_cert_pem = None

        session.add(server)

    if inserted == 0:
        try:
            session.commit()
        except IntegrityError:
            session.rollback()
            logger.warning(
                "Default VPN server bootstrap hit an integrity conflict; leaving existing inventory untouched."
            )
        return

    try:
        session.commit()
    except IntegrityError:
        session.rollback()
        logger.warning(
            "Default VPN server bootstrap hit an integrity conflict; leaving existing inventory untouched."
        )
