# Database package
"""Autogenerated SecureWave module overview.

This package initializer wires together the `database` package for the SecureWave backend.
See `docs/code-explanations/database/__init__.md` for the generated line-range walkthrough.
"""
