"""Autogenerated SecureWave module overview.

This database module configures base support for the SecureWave backend.
See `docs/code-explanations/database/base.md` for the generated line-range walkthrough.
"""

from sqlalchemy.orm import declarative_base

Base = declarative_base()

# Models are imported in main.py to avoid circular imports
# Alembic will discover them through Base.metadata
