#!/usr/bin/env python3
"""Generate backend code walkthroughs for the SecureWave Python app."""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOTS = [
    Path("main.py"),
    Path("auth"),
    Path("config"),
    Path("database"),
    Path("models"),
    Path("routes"),
    Path("routers"),
    Path("services"),
    Path("backend/services"),
]
DOCS_ROOT = ROOT / "docs" / "code-explanations"


@dataclass(frozen=True)
class Block:
    start: int
    end: int
    lines: list[str]


def iter_source_files() -> list[Path]:
    files: list[Path] = []
    for root in SOURCE_ROOTS:
        full_path = ROOT / root
        if full_path.is_file():
            files.append(full_path)
            continue
        files.extend(sorted(full_path.rglob("*.py")))
    return sorted(files)


def humanize(name: str) -> str:
    return name.replace("_", " ").replace("-", " ").strip()


def package_name(path: Path) -> str:
    relative = path.relative_to(ROOT)
    if relative.name == "__init__.py":
        return ".".join(relative.parent.parts) or "root"
    return ".".join(relative.with_suffix("").parts)


def module_summary(path: Path) -> str:
    relative = path.relative_to(ROOT)
    stem = relative.stem
    subject = humanize(stem if stem != "__init__" else relative.parent.name or "root package")
    top_level = relative.parts[0]

    if relative.name == "__init__.py":
        return (
            f"This package initializer wires together the `{package_name(path)}` package "
            "for the SecureWave backend."
        )
    if relative == Path("main.py"):
        return "This module bootstraps the SecureWave FastAPI application and its startup, middleware, and route registration."
    if top_level == "models":
        return f"This module defines the database model for {subject} records used by SecureWave."
    if top_level in {"routes", "routers"}:
        return f"This module exposes API handlers for {subject} features in the SecureWave backend."
    if top_level == "services":
        return f"This service module implements the business logic for {subject} operations."
    if top_level == "auth":
        return f"This authentication module handles {subject} responsibilities for SecureWave."
    if top_level == "config":
        return f"This configuration module defines settings and security policy for {subject}."
    if top_level == "database":
        return f"This database module configures {subject} support for the SecureWave backend."
    if top_level == "backend":
        return f"This backend service module manages low-level {subject} behavior for the VPN stack."
    return f"This module contains SecureWave backend code for {subject}."


def generated_docstring(path: Path) -> str:
    relative_doc = Path("docs") / "code-explanations" / path.relative_to(ROOT).with_suffix(".md")
    return (
        '"""Autogenerated SecureWave module overview.\n\n'
        f"{module_summary(path)}\n"
        f"See `{relative_doc.as_posix()}` for the generated line-range walkthrough.\n"
        '"""\n'
    )


def has_module_docstring(source: str) -> bool:
    try:
        module = ast.parse(source)
    except SyntaxError:
        return False
    return bool(ast.get_docstring(module))


def find_insertion_index(lines: list[str]) -> int:
    index = 0
    if index < len(lines) and lines[index].startswith("#!"):
        index += 1
    if index < len(lines) and re.match(r"#.*coding[:=]\s*[-\w.]+", lines[index]):
        index += 1
    while index < len(lines) and not lines[index].strip():
        index += 1
    while index < len(lines) and lines[index].lstrip().startswith("#"):
        index += 1
    while index < len(lines) and not lines[index].strip():
        index += 1
    return index


def ensure_module_docstring(path: Path) -> bool:
    source = path.read_text(encoding="utf-8")
    if has_module_docstring(source):
        return False
    lines = source.splitlines()
    index = find_insertion_index(lines)
    doc_lines = generated_docstring(path).splitlines()
    new_lines = lines[:index] + doc_lines + [""] + lines[index:]
    path.write_text("\n".join(new_lines).rstrip() + "\n", encoding="utf-8")
    return True


def blocks_for_source(source: str) -> list[Block]:
    lines = source.splitlines()
    blocks: list[Block] = []
    start: int | None = None
    current: list[str] = []

    for lineno, line in enumerate(lines, start=1):
        if line.strip():
            if start is None:
                start = lineno
            current.append(line)
            continue
        if start is not None:
            blocks.append(Block(start=start, end=lineno - 1, lines=current))
            start = None
            current = []

    if start is not None:
        blocks.append(Block(start=start, end=len(lines), lines=current))
    return blocks


def extract_name(line: str) -> str | None:
    match = re.match(r"(?:async\s+def|def|class)\s+([A-Za-z_][A-Za-z0-9_]*)", line.strip())
    return match.group(1) if match else None


def extract_docstring_text(lines: list[str]) -> str | None:
    text = "\n".join(lines)
    match = re.search(r'"""(.*?)"""', text, re.DOTALL) or re.search(r"'''(.*?)'''", text, re.DOTALL)
    if not match:
        return None
    content = " ".join(part.strip() for part in match.group(1).splitlines() if part.strip())
    return content.strip() or None


def summarize_imports(block: Block) -> str:
    modules: list[str] = []
    for line in block.lines:
        stripped = line.strip()
        if stripped.startswith("import "):
            imported = stripped.removeprefix("import ").split(",")
            modules.extend(part.strip().split(" as ")[0] for part in imported if part.strip())
        elif stripped.startswith("from "):
            modules.append(stripped.split()[1])
    unique = []
    for module in modules:
        root = module.split(".")[0]
        if root not in unique:
            unique.append(root)
    preview = ", ".join(unique[:8])
    if len(unique) > 8:
        preview += ", ..."
    return f"Imports the dependencies used later in this module, including {preview}."


def summarize_assignment(block: Block) -> str:
    names: list[str] = []
    for line in block.lines:
        stripped = line.strip()
        if stripped.startswith(("if ", "elif ", "else:", "for ", "while ", "try:", "with ", "return ", "@")):
            break
        if "=" not in stripped or "==" in stripped or stripped.startswith(("def ", "class ", "async def ")):
            continue
        left = stripped.split("=", 1)[0]
        for piece in left.split(","):
            candidate = piece.strip().lstrip("*")
            if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_\.]*", candidate):
                names.append(candidate)
    if not names:
        return "Initializes module-level variables and configuration used by later code."
    preview = ", ".join(dict.fromkeys(names[:6]))
    return f"Initializes module-level state or configuration such as `{preview}`."


def summarize_decorator_block(lines: list[str]) -> str:
    target_line = ""
    decorators: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("@"):
            decorators.append(stripped)
            continue
        target_line = stripped
        break

    name = extract_name(target_line)
    if decorators and "app.middleware" in decorators[0]:
        return f"Registers `{name}` as application middleware so each HTTP request passes through this handler."
    if decorators and ".exception_handler" in decorators[0]:
        return f"Registers `{name}` as a custom exception handler for this application."
    if decorators and any(".get(" in item or ".post(" in item or ".put(" in item or ".delete(" in item for item in decorators):
        return f"Registers the `{name}` endpoint with the API router."
    if name:
        return f"Applies decorators and defines `{name}` with the wrapped behavior declared above it."
    return "Applies decorators that modify the behavior of the following definition."


def summarize_control_flow(first: str) -> str:
    mapping = {
        "if ": "Runs conditional logic so the module only performs this setup when the required condition is met.",
        "elif ": "Continues the conditional branch for the surrounding decision tree.",
        "else:": "Provides the fallback branch when earlier conditions are not met.",
        "try:": "Attempts a potentially fragile operation and relies on later branches to handle failures safely.",
        "except ": "Handles a failure from the preceding `try` block.",
        "finally:": "Runs cleanup code whether the earlier block succeeds or fails.",
        "with ": "Opens a managed context so resources are cleaned up automatically after use.",
        "for ": "Loops over a collection to apply the same work to each item.",
        "while ": "Repeats work until the loop condition changes.",
        "return ": "Returns a value from the current function.",
    }
    for prefix, summary in mapping.items():
        if first.startswith(prefix):
            return summary
    return ""


def summarize_comment_block(block: Block) -> str:
    first_comment = block.lines[0].strip().lstrip("#").strip()
    if first_comment:
        return f"Comment block that explains the next section: {first_comment}."
    return "Comment block that documents the intent of the surrounding code."


def summarize_block(block: Block) -> str:
    significant = [line.strip() for line in block.lines if line.strip()]
    if not significant:
        return "Blank separator used to keep the file readable."
    first = significant[0]

    if all(line.startswith("#") for line in significant):
        return summarize_comment_block(block)
    if first.startswith(('"""', "'''")):
        return "Module or block docstring that describes the responsibility of this section."
    if all(line.startswith(("import ", "from ")) or line.startswith("#") for line in significant):
        return summarize_imports(block)
    if first.startswith("@"):
        return summarize_decorator_block(significant)
    if first.startswith(("async def ", "def ")):
        name = extract_name(first) or "function"
        doc = extract_docstring_text(block.lines)
        if doc:
            return f"Defines `{name}`. {doc.rstrip('.') }."
        return f"Defines the `{name}` function and the logic it executes."
    if first.startswith("class "):
        name = extract_name(first) or "class"
        doc = extract_docstring_text(block.lines)
        if doc:
            return f"Defines `{name}`. {doc.rstrip('.') }."
        return f"Defines the `{name}` class and the behavior it groups together."

    control_flow_summary = summarize_control_flow(first)
    if control_flow_summary:
        return control_flow_summary

    if "=" in first and "==" not in first:
        return summarize_assignment(block)

    preview = first if len(first) <= 100 else first[:97] + "..."
    return f"Implements this section of logic starting with `{preview}`."


def write_walkthrough(path: Path) -> None:
    relative = path.relative_to(ROOT)
    doc_path = DOCS_ROOT / relative.with_suffix(".md")
    doc_path.parent.mkdir(parents=True, exist_ok=True)

    source = path.read_text(encoding="utf-8")
    blocks = blocks_for_source(source)
    lines = [
        f"# `{relative.as_posix()}`",
        "",
        f"Purpose: {module_summary(path)}",
        "",
        "## Line Walkthrough",
    ]

    if not blocks:
        lines.extend(["", "- The file is currently empty."])
    else:
        lines.append("")
        for block in blocks:
            if block.start == block.end:
                line_range = f"L{block.start}"
            else:
                line_range = f"L{block.start}-L{block.end}"
            lines.append(f"- `{line_range}`: {summarize_block(block)}")

    doc_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_index(files: list[Path]) -> None:
    lines = [
        "# SecureWave Backend Code Explanations",
        "",
        "This folder contains autogenerated walkthroughs for the app-owned Python backend code.",
        "Each page explains a source file in line ranges so the code stays readable while the documentation remains detailed.",
        "",
        "## Covered Files",
        "",
    ]
    for path in files:
        relative = path.relative_to(ROOT)
        doc_path = relative.with_suffix(".md").as_posix()
        lines.append(f"- `{relative.as_posix()}` -> [{doc_path}]({doc_path})")

    (DOCS_ROOT / "README.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    files = iter_source_files()
    updated = 0
    for path in files:
        updated += int(ensure_module_docstring(path))
        write_walkthrough(path)
    write_index(files)
    print(f"Processed {len(files)} files.")
    print(f"Inserted module docstrings into {updated} files.")


if __name__ == "__main__":
    main()
