# Routers package
"""Autogenerated SecureWave module overview.

This package initializer wires together the `routers` package for the SecureWave backend.
See `docs/code-explanations/routers/__init__.md` for the generated line-range walkthrough.
"""
