# Models package
"""Autogenerated SecureWave module overview.

This package initializer wires together the `models` package for the SecureWave backend.
See `docs/code-explanations/models/__init__.md` for the generated line-range walkthrough.
"""
