from __future__ import annotations

from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, UniqueConstraint, JSON
from sqlalchemy.orm import relationship

from database.base import Base
from utils.time_utils import utcnow


class VPNCredential(Base):
    """
    Per-user, per-device credentials for non-WireGuard VPN protocols.

    Rationale:
    - WireGuard uses per-device public/private keys stored in `wireguard_peers`.
    - OpenVPN/IKEv2 commonly use username/password credentials.
    - Credentials are generated by the backend and stored encrypted at rest.
    """

    __tablename__ = "vpn_credentials"
    __table_args__ = (
        UniqueConstraint(
            "user_id",
            "device_id",
            "server_id",
            "protocol",
            name="uq_vpn_credentials_user_device_server_protocol",
        ),
    )

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    device_id = Column(Integer, ForeignKey("wireguard_peers.id"), nullable=False, index=True)
    server_id = Column(Integer, ForeignKey("vpn_servers.id"), nullable=False, index=True)

    protocol = Column(String(length=16), nullable=False, index=True)  # openvpn|ikev2
    credential_type = Column(String(length=32), nullable=False, default="username_password")
    username = Column(String(length=64), nullable=False)
    password_encrypted = Column(String, nullable=False)
    cert_serial = Column(String(length=128), nullable=True, index=True)
    cert_fingerprint_sha256 = Column(String(length=128), nullable=True)
    profile_expires_at = Column(DateTime, nullable=True)
    last_provisioned_at = Column(DateTime, nullable=True)
    last_rotated_at = Column(DateTime, nullable=True)
    revoked_at = Column(DateTime, nullable=True, index=True)
    revoke_reason = Column(String(length=128), nullable=True)
    revision = Column(Integer, nullable=False, default=1)
    provisioning_token_hash = Column(String(length=128), nullable=True)
    metadata_json = Column(JSON, nullable=True)

    created_at = Column(DateTime, default=utcnow, nullable=False)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow, nullable=False)

    # Relationships (optional, but useful for admin tooling)
    user = relationship("User", backref="vpn_credentials")
    device = relationship("WireGuardPeer", backref="vpn_credentials")
    server = relationship("VPNServer", backref="vpn_credentials")

    def __repr__(self) -> str:
        return (
            f"<VPNCredential(user_id={self.user_id}, device_id={self.device_id}, "
            f"server_id={self.server_id}, protocol={self.protocol}, "
            f"revision={self.revision}, revoked_at={self.revoked_at})>"
        )
